# Generated by Django 3.1.7 on 2021-03-29 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Income'), (2, 'Account'), (3, 'Expense')])),
                ('name', models.CharField(max_length=128)),
                ('actual_amount', models.FloatField()),
                ('planned_amount', models.FloatField()),
                ('icon', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('tags', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_transactions', to='main.account')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_transactions', to='main.account')),
            ],
        ),
    ]
