# Generated by Django 3.1.7 on 2021-04-03 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='planned_amount',
            field=models.FloatField(blank=True),
        ),
    ]
