# Generated by Django 3.1.7 on 2021-04-03 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210403_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='icon',
            field=models.CharField(blank=True, default='icon.png', max_length=255),
        ),
    ]
