# Generated by Django 3.1.7 on 2021-04-03 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210403_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='planned_amount',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
