# Generated by Django 3.1.7 on 2021-04-03 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_auto_20210403_0721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.customuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
