# Generated by Django 3.1.7 on 2021-04-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210405_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='actual_amount',
            field=models.FloatField(default=0),
        ),
    ]
